services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/dashboard:/app
      - /app/node_modules/
      - /app/.next/
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:${BACKEND_PORT}
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      args:
        BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
<<<<<<< HEAD
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
=======
      - DB_HOST=db
      - DB_USER=user
      - DB_PASS=pass # TODO move to secure env
      - DB_NAME=app_db
>>>>>>> e4eb3a9 (fixed analysis SQL INSERT example)
    depends_on:
      - database

  analysis:
    build:
      context: ./analysis
    environment:
<<<<<<< HEAD
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
=======
      - DB_HOST=database
      - DB_USER=user
      - DB_PASS=pass # TODO move to secure env
      - DB_NAME=app_db
>>>>>>> e4eb3a9 (fixed analysis SQL INSERT example)
    depends_on:
      - database

  database:
    image: mysql:8
    environment:
<<<<<<< HEAD
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
=======
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: app_db
      MYSQL_ROOT_PASSWORD: rootpass # TODO move to secure env
>>>>>>> e4eb3a9 (fixed analysis SQL INSERT example)
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d 
    ports:
      - "${DB_PORT}:${DB_PORT}"

volumes:
  db_data:
